#!/bin/sh

module="vd_device"
char_device_tx="vc_tx"
char_device_rx="vc_rx"
mode="664"

# invoke insmod with all arguments we got
# and use a pathname, as newer modutils don't look in . by default
/sbin/insmod ./$module.ko $* || exit 1

ifconfig veth0 up
ifconfig veth0 192.168.5.1

# remove stale nodes
rm -f /dev/$char_device_tx
rm -f /dev/$char_device_rx

major_tx=$(awk -v keyword=$char_device_tx '$0 ~ keyword {print $1}' /proc/devices)
major_rx=$(awk -v keyword=$char_device_rx '$0 ~ keyword {print $1}' /proc/devices)

mknod /dev/$char_device_tx c $major_tx 1
mknod /dev/$char_device_rx c $major_rx 0

# give appropriate group/permissions, and change the group.
# Not all distributions have staff, some have "wheel" instead.
group="staff"
grep -q '^staff:' /etc/group || group="wheel"

chgrp $group /dev/$char_device_tx
chgrp $group /dev/$char_device_rx

chmod $mode /dev/$char_device_tx
chmod $mode /dev/$char_device_rx
